id: I692AD6F5
ocr_import_info:
  timestamp: '2023-08-22T03:30:49.671093+00:00'
  batch_id: batch-5753
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-22 03:58:43.047193+00:00
last_modified: 2023-08-22 03:58:43.047199+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1NLM3260
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1NLM3260
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དབུ་མ་འཇུག་པའི་མཐའ་དཔྱོད་ལུང་རིགས་སྒྲོན་མེ།
  languages:
  - bo
  author: འཇམ་དབྱངས་བཞད་པ ༠༢་དཀོན་མཆོག་འཇིགས་མེད་དབང་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.9654360500155136
  ocr_word_median_confidence_index: 0.9963403
bases:
  I1NLM3260_001:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1NLM3260_001
      total_pages: 484
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I1NLM3260_001.txt
    statistics:
      ocr_word_median_confidence_index: 0.9963403
      ocr_word_mean_confidence_index: 0.9654360500155136
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
